include_directories(src)
include_directories(3rd_party)
include_directories(3rd_party/LiteScene)
include_directories(3rd_party/LiteScene/loader_utils)
include_directories(3rd_party/heavy_rt/core)
include_directories(3rd_party/heavy_rt/core/common)
